### ISSUE TITLE
TypeError: super() takes at least 1 argument (0 given)

### ISSUE THREAD

**Issue by Hellmark** [mitchjeitani/catacomb#7]
after install, this is the only output I get, no matter what.

Traceback (most recent call last):
  File "/usr/local/bin/catacomb", line 7, in <module>
    from catacomb.entry_points import catacomb_entry
  File "/home/kbrown/.local/lib/python2.7/site-packages/catacomb/entry_points.py", line 14, in <module>
    @pass_context
  File "/home/kbrown/.local/lib/python2.7/site-packages/click/decorators.py", line 115, in decorator
    cmd = _make_command(f, name, attrs, cls)
  File "/home/kbrown/.local/lib/python2.7/site-packages/click/decorators.py", line 89, in _make_command
    callback=f, params=params, **attrs)
  File "/home/kbrown/.local/lib/python2.7/site-packages/catacomb/utils/plugin_loader.py", line 12, in __init__
    super().__init__(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

**Comment by jaxxstorm** [comment]
Same issue here

**Comment by mitchjeitani** [comment]
Unfortunately, catacomb doesn't support Python version 2.7. I had plans to add support for it but ultimately decided not to due to constraints with some of the modules I'm using.

I will investigate the work needed to support earlier versions of Python but for now, if you would like to use catacomb, try using one of the latest versions of Python (3.4+). If you already have newer versions of Python you may need to install using `pip3 install catacomb` - depending on how you've set up your paths.

**Comment by jaxxstorm** [comment]
Thanks for the pointer. I had installed via python3 on homebrew, but the shebang line is hardcoded to `/usr/bin/python`.

I modified `/usr/local/bin/catacomb` to use `#!/usr/bin/env python3` and it worked
